// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type EditTodo struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
}

type FetchTodo struct {
	ID int `json:"id"`
}

type NewRole struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	RoleID   int    `json:"roleId"`
}
